name: mandelbrot_set
description: "The Mandelbrot Set"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bitsdojo_window: ^0.1.5
  flutter:
    sdk: flutter

  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  shaders:
    - assets/shaders/mandelbrots.frag

  assets:
    - assets/
